const ActionTypes = {
  CAN_CASTLE: "CAN_CASTLE",
  STALEMATE: "STALEMATE",
  CLEAR_CANDIDATE_MOVES: "CLEAR_CANDIDATE_MOVES",
  GENERATE_CANDIDATE_MOVES: "GENERATE_CANDIDATE_MOVES",
  NEW_MOVE: "NEW_MOVE",
  NEW_GAME: "NEW_GAME",
  PROMOTION_OPEN: "PROMOTION_OPEN",
  PROMOTION_CLOSE: "PROMOTION_CLOSE",
};

export default ActionTypes;
